/* Code generated by ecgen from engine-contracts/contracts.yaml. DO NOT EDIT.
 *
 * P/D orchestration engine wire IDs (proxy_epval_t.pd_engine and the wire
 * kv_engine_type encoding). Values are ABI-frozen: they cross the Go->C
 * boundary as numbers and must never be renumbered. Adding an engine =
 * manifest change + regeneration, never a hand edit here. An ID absent
 * from this header is unknown to the data plane and MUST fail closed
 * (no default-to-vLLM fallback).
 */
#ifndef __SOCKPROXY_PD_IDS_H__
#define __SOCKPROXY_PD_IDS_H__

#define PD_ENGINE_VLLM 0
#define PD_ENGINE_SGLANG 1
#define PD_ENGINE_TRTLLM 2

/* Highest generated engine ID; anything above is unknown. */
#define PD_ENGINE_ID_MAX 2

/* Sentinel for an unknown wire value: pd_engine_from_kv_engine_type()
 * returns it instead of defaulting to a real engine, and
 * pd_dialect_resolve() maps it (and anything else unknown) to NULL. */
#define PD_ENGINE_INVALID 0xFF

#endif /* __SOCKPROXY_PD_IDS_H__ */
